name: Release

on:
  workflow_dispatch

jobs:

  release:
    name: Release
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      PROJECT_PATH: "src/Vajehbaz/Vajehbaz.csproj"
      RELEASE_FILES_PATH: ".tmp/release-files"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Download necessary tools
        run: |
          cd tools
          ./GetNetRuntimes.ps1
          ./GetInnoSetup.ps1

      - name: Get project version
        run: |
          $version = ([xml](Get-Content ${{ env.PROJECT_PATH }})).Project.PropertyGroup.Version
          'PRPJECT_VERSION=' + $version >> $env:GITHUB_ENV

      - name: Get latest version changelog
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: v${{ env.PRPJECT_VERSION }}

      - name: Clean
        run: |
          dotnet clean
          $binPath = Join-Path (Split-Path ${{ env.PROJECT_PATH }} -Parent) '\bin\release\net6.0-windows'
          if(Test-Path -LiteralPath $binPath) {Remove-Item -Recurse -Force $binPath}

      - name: Build
        run: cd tools && ./BuildSetups.ps1

      - name: Copy builds to tmp
        shell: bash
        run: |
          mkdir -p ${{ env.RELEASE_FILES_PATH }}
          find 'src/Vajehbaz/bin/release/net6.0-windows/' \( -name "VajehbazSetup*.exe" -or -name "*portable.exe" \) | xargs cp -t ${{ env.RELEASE_FILES_PATH }}

      - name: Build SHA-256 Checksum(s)
        shell: bash
        run: cd ${{ env.RELEASE_FILES_PATH }} && find . -name '*.exe' -exec sha256sum {} \; > checksums.sha256

      - name: Prepend changelog to release notes
        shell: bash
        run: |
          echo -e "${{ steps.changelog_reader.outputs.changes }}" >> '.tmp/release-notes.md'
          echo -e "### SHA-256 checksums\n" > .tmp/checksums.md
          cd ${{ env.RELEASE_FILES_PATH }} && for file in *; do echo -e "- ** $file ** \n  - $(sha256sum $file | awk '{ print $1 }')\n"; done >> ../checksums.md && cd ../..
          cat .tmp/checksums.md >> .tmp/release-notes.md

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.repository.name }} v${{ env.PRPJECT_VERSION }}
          tag_name: v${{ env.PRPJECT_VERSION }}
          body_path: .tmp/release-notes.md
          files: ${{ env.RELEASE_FILES_PATH }}/*
